

service: qi-audit-kinesis

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  environment: ${file(./src/config/env.yml):${opt:stage, self:custom.defaults.stage}}
    
functions:
  eventsHttp:
    handler: src/handlers/http.logEvent
    events:
      - http:
          method: POST
          path: /logEvent
          cors: true
  auditStream:
    handler: src/handlers/audit-stream.auditLog
    events:
      - stream:
          type: kinesis
          #arn: need an arn
          batchSize: 100
          startingPosition: LATEST
  
package:
  include:
    - src/**/*
  
plugins:
 - serverless-webpack
 - serverless-offline
 - serverless-domain-manager


custom:
  defaults:
    stage: dev
  webpack:
    includeModules: true # enable auto-packing of external modules
  #customDomain:
    #domainName: banana-server.qidevteam.com
    #basePath: ''
    #stage: production
    #createRoute53Record: true